services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

    volumes:
      - database-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7
    volumes:
      - redis-data:/data

    restart: always
  
volumes:
  redis-data:
  database-data:
