
services:

  backend:
    image: taskplatform
    container_name: backend
    env_file:
      - .env
    ports:
      - 8080:8080

    networks:
      - backend-network

    volumes:
      - ./src:/user/src/app

    depends_on:
      - database
      - redis
      - loki

  database:
    image: postgres
    container_name: database
    restart: always
    # ports: # remove this for access database in localhost
    #  - 5432:5432
    env_file:
      - .env

    networks:
      - backend-network

    volumes:
      - database-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    networks:
      - backend-network

    # ports:
    #  - 6379:6379

    volumes:
      - redis-data:/data

    restart: always

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:      
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    networks:
      - backend-network
    user: "0"
    env_file:
      - .env
    depends_on:
      - prometheus
      - redis-exporter
      - database
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - backend-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped 

  redis-exporter:
    image: bitnami/redis-exporter
    container_name: redis-exporter
    command: 
      - "--redis.addr=redis://redis:6379"
    networks:
      - backend-network
    depends_on:
      - redis
    
  postgres-exporter:
    image: bitnami/postgres-exporter
    container_name: postgres-exporter
    env_file:
      - .env
    networks:
      - backend-network
    depends_on:
      - database

  loki:
    # image: grafana/loki:2.3.0
    image: grafana/loki:latest
    container_name: loki
    # ports: # remove this for access loki in localhost
    #   - 3100:3100
    networks:
      - backend-network
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - loki-data:/loki
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    user: "0"

volumes:
  redis-data:
  database-data:
  loki-data:

networks:
  backend-network:
    driver: bridge