apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: redis-exporter
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    isDefault: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true